#+SETUPFILE: settings.org
#+INFOJS_OPT: view:overview toc:nil
#+TITLE: Matt's Home Page
#+INDEX: Home Page
Click on a heading to see more.  Press ~i~ to change views.

My permanent link is https://alum.mit.edu/www/junker.

This page is under construction.  My original page is at
https://sites.google.com/site/mkjunker.  Please look there for missing
content, which will be moved here soon (I hope).  [2021-02-10 Wed]

* Calendar
  # settings, click on calendar, "integrate"
  #+begin_export html
  <iframe src="https://calendar.google.com/calendar/embed?height=400&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=America%2FChicago&amp;src=bDllc2k2NGprbmQ5bWY3OTU2MTFlY2k5cWNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=OWc3amJubTR2bWkyZ3B0MTIyZWdjbmphZG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=aWg3aGowMDFkODg4bG9qbG9jZzFwcjQ5ZHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=dW9pdnJybDIxajQ5ZjZiNXQ1OG9nbTNybG9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=OHE1Y25rdGhjMWUxa2M0ZG12M2s5ZTJpOHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=I2RheW51bUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&amp;src=bmZsXzlfJTQ3cmVlbislNDJheSslNTBhY2tlcnMjc3BvcnRzQGdyb3VwLnYuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=bWxiXzhfJTRkaWx3YXVrZWUrJTQycmV3ZXJzI3Nwb3J0c0Bncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&amp;src=bmJhXzE1XyU0ZGlsd2F1a2VlKyU0MnVja3Mjc3BvcnRzQGdyb3VwLnYuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=bmNhYWZfMTAyXyU0ZWF2eSslNGRpZHNoaXBtZW4jc3BvcnRzQGdyb3VwLnYuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=bmNhYWZfMzZfJTU3aXNjb25zaW4rJTQyYWRnZXJzI3Nwb3J0c0Bncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&amp;src=aHQzamxmYWFjNWxmZDYyNjN1bGZoNHRxbDhAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;color=%23AD1457&amp;color=%239E69AF&amp;color=%23B39DDB&amp;color=%23E67C73&amp;color=%23F09300&amp;color=%23616161&amp;color=%23616161&amp;color=%23616161&amp;color=%23616161&amp;color=%23616161&amp;color=%23616161&amp;color=%23616161&amp;mode=AGENDA&amp;showTitle=0" style="border:solid 1px #777" width="500" height="400" frameborder="0" scrolling="no"></iframe>
  #+end_export
* Weather
  #+begin_export html
  <a class="weatherwidget-io" href="https://forecast7.com/en/43d24n87d98/thiensville/?unit=us" data-label_1="THIENSVILLE" data-label_2="WEATHER" data-theme="original" >THIENSVILLE WEATHER</a>
  <script>
  !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
  </script>
  #+end_export

  #+begin_export html
  <iframe src="kmwc.html" style="border: solid thin #3366ff; width:500px; height:300px"></iframe>
  #+end_export
  # +begin_export html
  # <iframe src="kmke.html" style="border: solid thin #3366ff; width:200px; height:300px"></iframe>
  # +end_export
  # +begin_export html
  # <iframe src="https://www.ndbc.noaa.gov/data/latest_obs/pwaw3.txt" style="border: solid thin #3366ff; width:200px; height:300px"></iframe>
  # +end_export
  #+begin_export html
  <iframe src="https://www.ndbc.noaa.gov/widgets/station_page.php?station=PWAW3" style="border: solid thin #3366ff; width:200px; height:300px"></iframe>
  #+end_export
  #+begin_export html
  <iframe src="https://www.ndbc.noaa.gov/widgets/station_page.php?station=MLWW3" style="border: solid thin #3366ff; width:200px; height:300px"></iframe>
  #+end_export
  #+begin_export html
  <iframe src="https://www.ndbc.noaa.gov/widgets/station_page.php?station=45013" style="border: solid thin #3366ff; width:200px; height:300px"></iframe>
  #+end_export
  #+begin_export html
  <iframe src="https://www.ndbc.noaa.gov/widgets/station_page.php?station=45007" style="border: solid thin #3366ff; width:200px; height:300px"></iframe>
  #+end_export
  # +begin_export html
  # <iframe name="KMKE" style="border: 0; frameborder: 0;" width="325" height="500" scrolling="auto" src="https://www.weather.gov/hfo/WWAwidget#KMKE"></iframe>
  # +end_export
  # https://www.ndbc.noaa.gov/rss/ndbc_obs_search.php?lat=43.23706N&lon=87.97032W&radius=100

* Sports
  #+begin_export html
  <script type="text/javascript"
  src="https://widgets.sports-reference.com/wg.fcgi?script=br_standings&amp;params=br_standings_lg:NL,br_standings_div:C,br_standings_css:1&amp;css=1"></script>
  #+end_export
  #+begin_export html
  <script type="text/javascript" src="https://widgets.sports-reference.com/wg.fcgi?script=bbr_standings&amp;params=bbr_standings_conf:E,bbr_standings_css:0&amp;css=1"></script>
  <script src="https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2FMIL%2F2021_games.html&div=div_games"></script>
  #+end_export
  #+begin_export html
  <script src="https://widgets.sports-reference.com/wg.fcgi?css=1&site=cfb&url=%2Fcfb%2Fschools%2Fnavy%2F2020-schedule.html&div=div_schedule"></script>
  #+end_export
* Junker's Laws
  1. If you're using Excel, you're probably doing it wrong.
  2. The best review is trying to implement the code or test.

* Documents and Media
** Emacs Files
   + https://github.com/mkjunker contains all of my public Emacs lisp
     files.
** Navy Documents
   #+INDEX: navy
   + [[https://drive.google.com/file/d/1RMurM18N3aC_bCx8Nn70R4xZGgbomD_G/view?usp=drive_web][USS /Woodrow Wilson/ inactivation program, 24 September 1993]]
   + [[https://drive.google.com/file/d/1LqZOCDkWdKj85EVnD5DiRJNeUK7o25W6/view?usp=drive_web][Flooding in the Fan Room, /Fathom/ Magazine, September/October 1993]]
   + [[https://drive.google.com/file/d/0B65OWczbRgzAWWxiTU1RTFAwRXc/view?usp=drive_web][A Review of the United States Naval Nuclear Propulsion Program, June 1987]]
   + [[https://drive.google.com/file/d/0B65OWczbRgzAR0kzeF9FYXRIRmc/view?usp=drive_web][Polaris-Poseidon Fleet Ballistic Missle Fact Sheet 1967]]
** Sounds
   #+INDEX: navy
   + USS /Woodrow Wilson/ diving alarm, [[https://freesound.org/people/mkjunker/sounds/156672/][WAV version]], [[https://drive.google.com/file/d/0B65OWczbRgzAaWxNOEVpQWx0am8/view?usp=drive_web][MP3 version]]
   + [[https://drive.google.com/file/d/0B65OWczbRgzAOTNZTEJDdTFCVEE/view?usp=drive_web]["Just As I Am"]]
** Pictures
   #+INDEX: navy
   + [[https://drive.google.com/file/d/0B65OWczbRgzAb0tqdDJ5SnFVak0/view?usp=drive_web][USS /Woodrow Wilson/ wardroom, outboard of USS /Orion/, Santo Stefano Island, Italy, 1992]]
** Postscript Files
   # consider moving to github
   /The following plotting tools are provided as-is. The author makes
   no guarantees about their accuracy or usefulness. Use them at your
   own risk./

   Don't have a Postscript printer? Try ([[http://pages.cs.wisc.edu/~ghost/][Ghostscript and Ghostview
   (GSView for Windows environments)]]. These tools allow viewing and
   printing Postscript files.

   Some of the Postscript files were developed using MetaPost. A Windows
   version of MetaPost is included with MikTeX at The MikTeX Project
   Page. For more on MetaPost, try:
   * [[http://www.tug.org/metapost.html][TUG's MetaPost page]]

   Files:
   + maneuvering board: [[https://drive.google.com/file/d/0B65OWczbRgzAREJJaHV0d1FRZmM/view?usp=drive_web][postscript]], [[https://drive.google.com/file/d/0B65OWczbRgzATkx4YWF3ZEdEcGM/view?usp=drive_web][MetaPost source]] [[https://msi.nga.mil/media/ManeuveringBoard.pdf][PDF from NGA]] https://msi.nga.mil/Publications/RNMB
   + navigation plot: [[https://drive.google.com/file/d/0B65OWczbRgzANUNrYnBvUHVGWU0/view?usp=drive_web][postscript]], [[https://drive.google.com/file/d/0B65OWczbRgzAbnJMRHN2SmJsNGs/view?usp=drive_web][MetaPost source]]
   + wind chill chart: [[https://drive.google.com/file/d/0B65OWczbRgzAd2YtSDBoVUdrcGs/view?usp=drive_web][postscript]], [[https://drive.google.com/file/d/0B65OWczbRgzAbkRRdFNzcmVnVzQ/view?usp=drive_web][gnuplot source]]
   /TO DO: move these files./
* Sheepshead
  Trump Precedence: \\
  Q\clubs Q\spades Q\hearts Q\diamond   J\clubs J\spades J\hearts
  J\diamond A\diamond 10\diamond K\diamond 9\diamond 8\diamond
  7\diamond

  Fail Precedence: \\
  (\clubs \spades \diamond) A 10 K 9 8 7

  |      <r> |    |      |       |       |        |     |
  |   *Card* |  A |   10 |     K |     Q |      J |     |
  | *Points* | 11 |   10 |     4 |     3 |      2 |     |

  |           <r> | <c> | <c>  |  <c>  |  <c>  |  <c>   | <c> |
  |        Points |  0  | 1-30 | 31-60 | 61-90 | 91-119 | 120 |
  | Partner Score | +3  |  +2  |  +1   |  -1   |   -2   | -3  |
  
# +INCLUDE: documents.org :only-contents t

* Page 2
** Text
   #+INDEX: text
   Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non
   orci commodo lobortis.  Proin neque massa, cursus ut, gravida ut,
   lobortis eget, lacus.  Sed diam.  Praesent fermentum tempor tellus.
   Nullam tempus.  Mauris ac felis vel velit tristique imperdiet.  Donec
   at pede.  Etiam vel neque nec dui dignissim bibendum.  Vivamus id
   enim.  Phasellus neque orci, porta a, aliquet quis, semper a, massa.
   Phasellus purus.  Pellentesque tristique imperdiet tortor.  Nam
   euismod tellus id erat.

** Math
   #+INDEX: math
   $\sin(x) / x$
 # +INCLUDE: page2.org :only-contents t

* Links
  #+INDEX: links
  # + [[./documents.org][Documents and Media]]
  # + [[./page2.org][Page 2]]
  + Permanent link to my home page: https://alum.mit.edu/www/junker
  + My other page (soon to be redundant):
    https://sites.google.com/site/mkjunker
  + [[./sitemap.org][Site map]]



# https://stackoverflow.com/questions/51415911/emacs-org-mode-how-to-choose-font-when-exporting-to-html
# TO DO:
# org-html-postamble-format
# :html-postamble
# http://juanjose.garciaripoll.com/blog/org-mode-html-templates/index.html
